"""
Django settings for triplex_frontend project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from os import path, getenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#Allowed species
ALLOWED_SPECIES = [
        ("hsapiens", "hsapiens"),
        ("mmusculus","mmusculus")
]

#Constants:
BACKEND_URL = getenv("BACKEND_SERVER_URL")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenv("DJANGO_SECURE_KEY")

#HMAC Secret key. Warning_ keep the key used in production safe
HMAC_KEY = getenv("HMAC_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(getenv("DEBUG"))
ALLOWED_HOSTS = getenv('ALLOWED_HOSTS').split(',')

#App parameters (possibly to be moved to env variables on deploy..?)
#Rename of file names
SSRNA_BASE_NAME = getenv("SSRNA_BASE_NAME")
DSDNA_BASE_NAME = getenv("DSDNA_BASE_NAME")
DSDNA_BED_BASE_NAME = getenv("DSDNA_BED_BASE_NAME")
SSRNA_HEADER = getenv("SSRNA_HEADER")
#Files and urls
FILE_UPLOAD_MAX_MEMORY_SIZE = int(getenv("FILE_UPLOAD_MAX_MEMORY_SIZE"))
DSDNA_MAX_SIZE = int(getenv("DSDNA_MAX_SIZE"))
SSRNA_MAX_SIZE = int(getenv("SSRNA_MAX_SIZE"))


MEDIA_ROOT = getenv("MEDIA_ROOT")
MEDIA_URL = getenv("MEDIA_URL")
CLIENT_URL = getenv("CLIENT_URL")
MEDIA_ROOT_ABS_PATH = path.join(path.abspath(path.dirname(__name__)), MEDIA_ROOT)
#Cleanup service
RUN_CLEANUP_EVERY_HOURS = int(getenv("RUN_CLEANUP_EVERY_HOURS"))
CLEANUP_AFTER_HOURS = int(getenv("CLEANUP_AFTER_HOURS"))
#Email config
EMAIL_USE_TLS = bool(getenv("EMAIL_USE_TLS"))
EMAIL_HOST = getenv("EMAIL_HOST")
EMAIL_HOST_USER = getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = getenv("EMAIL_HOST_PASSWORD")
EMAIL_PORT = int(getenv("EMAIL_PORT"))
#Admin
ADMINS = [ (elem.split(",")[0], elem.split(",")[1]) for elem in getenv("ADMINS").split(";")]

# Application definition
CORS_ALLOW_ALL_ORIGINS = bool(getenv("CORS_ALLOW_ALL_ORIGINS"))


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    'rest_framework',
    'triplex',
    'token_queue_mng',
    'results_mng'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = 'triplex_frontend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'triplex_frontend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.{}'.format(
                getenv('DATABASE_ENGINE')
            ),
         'NAME': getenv('DATABASE_NAME'),
         'USER': getenv('DATABASE_USERNAME', ''),
         'PASSWORD': getenv('DATABASE_PASSWORD', 'triplex'),
         'HOST': getenv('DATABASE_HOST', ''), 
         'PORT': getenv('DATABASE_PORT', 0)
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
