# Generated by Django 4.2.6 on 2024-05-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('results_mng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StabilityTestJobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Created', 'Created'), ('Submitted', 'Submitted'), ('Ready', 'Ready'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], default='Created', max_length=16)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('triplex_params', models.JSONField()),
                ('base_path', models.CharField(max_length=64, unique=True)),
                ('species', models.CharField(choices=[('hsapiens', 'hsapiens'), ('mmusculus', 'mmusculus')], default=None, max_length=32, null=True)),
                ('ssRNA_fasta', models.FileField(default=None, null=True, upload_to='')),
                ('genes_all', models.FileField(default=None, null=True, upload_to='')),
                ('genes_of_interest', models.FileField(default=None, null=True, upload_to='')),
                ('rawLogsSTDOUT', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('rawLogsSTDERR', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('STABILITY_BEST', models.FileField(default=None, null=True, upload_to='')),
                ('STABILITY_NORM', models.FileField(default=None, null=True, upload_to='')),
                ('STABILITY_BEST_FGSEA_RES', models.FileField(default=None, null=True, upload_to='')),
                ('STABILITY_BEST_LEADING_EDGE', models.FileField(default=None, null=True, upload_to='')),
                ('STABILITY_BEST_ENRICHMENT_PLOT', models.FileField(default=None, null=True, upload_to='')),
                ('STABILITY_BEST_STABILITY_COMP_BOXPLOT', models.FileField(default=None, null=True, upload_to='')),
                ('STABILITY_BEST_STABILITY_COMP', models.FileField(default=None, null=True, upload_to='')),
                ('STABILITY_NORM_FGSEA_RES', models.FileField(default=None, null=True, upload_to='')),
                ('STABILITY_NORM_LEADING_EDGE', models.FileField(default=None, null=True, upload_to='')),
                ('STABILITY_NORM_ENRICHMENT_PLOT', models.FileField(default=None, null=True, upload_to='')),
                ('STABILITY_NORM_STABILITY_COMP_BOXPLOT', models.FileField(default=None, null=True, upload_to='')),
                ('STABILITY_NORM_STABILITY_COMP', models.FileField(default=None, null=True, upload_to='')),
                ('cleaned_up', models.BooleanField(default=False)),
                ('export_tarball', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('export_hash', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('ssRNA_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='results_mng.longesttranscript')),
            ],
        ),
    ]
