# Generated by Django 4.2.6 on 2023-12-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter_stability_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stabilitytestjobdata',
            name='STABILITY_BEST',
            field=models.FileField(default=None, null=True, upload_to='stability_best/'),
        ),
        migrations.AddField(
            model_name='stabilitytestjobdata',
            name='STABILITY_BEST_ENRICHMENT_PLOT',
            field=models.FileField(default=None, null=True, upload_to='stability_best_enrichment_plot/'),
        ),
        migrations.AddField(
            model_name='stabilitytestjobdata',
            name='STABILITY_BEST_FGSEA_RES',
            field=models.FileField(default=None, null=True, upload_to='stability_best_fgsea_res/'),
        ),
        migrations.AddField(
            model_name='stabilitytestjobdata',
            name='STABILITY_BEST_LEADING_EDGE',
            field=models.FileField(default=None, null=True, upload_to='stability_best_leading_edge/'),
        ),
        migrations.AddField(
            model_name='stabilitytestjobdata',
            name='STABILITY_BEST_STABILITY_COMP',
            field=models.FileField(default=None, null=True, upload_to='stability_best_stability_comp/'),
        ),
        migrations.AddField(
            model_name='stabilitytestjobdata',
            name='STABILITY_BEST_STABILITY_COMP_BOXPLOT',
            field=models.FileField(default=None, null=True, upload_to='stability_best_stability_comp_boxplot/'),
        ),
        migrations.AddField(
            model_name='stabilitytestjobdata',
            name='STABILITY_NORM',
            field=models.FileField(default=None, null=True, upload_to='stability_norm/'),
        ),
        migrations.AddField(
            model_name='stabilitytestjobdata',
            name='STABILITY_NORM_ENRICHMENT_PLOT',
            field=models.FileField(default=None, null=True, upload_to='stability_norm_enrichment_plot/'),
        ),
        migrations.AddField(
            model_name='stabilitytestjobdata',
            name='STABILITY_NORM_FGSEA_RES',
            field=models.FileField(default=None, null=True, upload_to='stability_norm_fgsea_res/'),
        ),
        migrations.AddField(
            model_name='stabilitytestjobdata',
            name='STABILITY_NORM_LEADING_EDGE',
            field=models.FileField(default=None, null=True, upload_to='stability_norm_leading_edge/'),
        ),
        migrations.AddField(
            model_name='stabilitytestjobdata',
            name='STABILITY_NORM_STABILITY_COMP',
            field=models.FileField(default=None, null=True, upload_to='stability_norm_stability_comp/'),
        ),
        migrations.AddField(
            model_name='stabilitytestjobdata',
            name='STABILITY_NORM_STABILITY_COMP_BOXPLOT',
            field=models.FileField(default=None, null=True, upload_to='stability_norm_stability_comp_boxplot/'),
        ),
    ]
