# Generated by Django 4.2.6 on 2024-02-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter_stability_test', '0002_stabilitytestjobdata_stability_best_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stabilitytestjobdata',
            name='export_hash',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='stabilitytestjobdata',
            name='export_tarball',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stabilitytestjobdata',
            name='STABILITY_BEST',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stabilitytestjobdata',
            name='STABILITY_BEST_ENRICHMENT_PLOT',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stabilitytestjobdata',
            name='STABILITY_BEST_FGSEA_RES',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stabilitytestjobdata',
            name='STABILITY_BEST_LEADING_EDGE',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stabilitytestjobdata',
            name='STABILITY_BEST_STABILITY_COMP',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stabilitytestjobdata',
            name='STABILITY_BEST_STABILITY_COMP_BOXPLOT',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stabilitytestjobdata',
            name='STABILITY_NORM',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stabilitytestjobdata',
            name='STABILITY_NORM_ENRICHMENT_PLOT',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stabilitytestjobdata',
            name='STABILITY_NORM_FGSEA_RES',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stabilitytestjobdata',
            name='STABILITY_NORM_LEADING_EDGE',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stabilitytestjobdata',
            name='STABILITY_NORM_STABILITY_COMP',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stabilitytestjobdata',
            name='STABILITY_NORM_STABILITY_COMP_BOXPLOT',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
