# Generated by Django 4.1.1 on 2023-08-19 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('results_mng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('job_name', models.CharField(default=None, max_length=64, null=True)),
                ('email_address', models.EmailField(default=None, max_length=254, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='results_mng.jobdata')),
            ],
        ),
    ]
