# Generated by Django 4.1.1 on 2023-05-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.AutoField(primary_key=True, serialize=False)),
                ('_token_state', models.CharField(choices=[('Sb', 'Submitted'), ('Rd', 'Ready'), ('Ex', 'Expired'), ('Cn', 'Cancelled'), ('Fl', 'Failed')], default='Sb', max_length=2)),
            ],
        ),
    ]
