# Generated by Django 4.1.1 on 2023-06-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_queue_mng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(editable=False, max_length=33, primary_key=True, serialize=False, unique=True),
        ),
    ]
