# Generated by Django 4.2.6 on 2023-11-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_queue_mng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='token_queue_mng.token')),
            ],
        ),
    ]
