# Generated by Django 4.2.6 on 2023-12-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_queue_mng', '0002_dbd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='job',
            new_name='standard_job',
        ),
    ]
