# Generated by Django 4.2.6 on 2023-12-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('results_mng', '0016_geneindnatargetsite_results_mng_name_33d2de_idx'),
        ('token_queue_mng', '0003_rename_job_token_standard_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='standard_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='results_mng.jobdata'),
        ),
    ]
