# Generated by Django 4.1.1 on 2023-06-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('results_mng', '0013_jobdata_dsdna_precomputed_target'),
        ('token_queue_mng', '0003_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='results_mng.jobdata'),
        ),
    ]
