# Generated by Django 4.2.6 on 2023-12-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promoter_stability_test', '0001_initial'),
        ('token_queue_mng', '0004_alter_token_standard_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='promoter_stability_test_job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='promoter_stability_test.stabilitytestjobdata'),
            preserve_default=False,
        ),
    ]
