# Generated by Django 4.2.6 on 2023-12-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_queue_mng', '0006_alter_token_promoter_stability_test_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='promoter_stability_test_job',
        ),
    ]
