# Generated by Django 4.2.6 on 2023-12-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promoter_stability_test', '0001_initial'),
        ('token_queue_mng', '0007_remove_token_promoter_stability_test_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='promoter_stability_test_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promoter_stability_test.stabilitytestjobdata'),
        ),
    ]
